name: aizuchi_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  # util
  envied:
  freezed_annotation:
  shared_preferences:
  timezone:
  auto_route:
  intl:
  url_launcher:
  roggle:
  uuid:
  # 課金
  purchases_flutter: ^6.25.0

  # firebase
  firebase_core: ^2.30.0
  firebase_auth:
  firebase_database:
  cloud_firestore:
  google_sign_in:

  # riverpod
  riverpod:
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:
  hooks_riverpod:

  # UI
  fl_chart:
  carousel_slider:
  sign_in_button:
  flutter_datetime_picker_plus:

  # add function
  # 未設定
  flutter_local_notifications: ^16.3.2
  email_validator: ^2.1.17
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  http: ^1.1.0
  flutter_timezone: ^1.0.8
  in_app_purchase: ^3.1.11
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^7.0.0

dev_dependencies:
  auto_route_generator:
  build_runner:
  riverpod_generator:
  envied_generator:
  freezed:
  json_serializable:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100
    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic-Black.ttf
          weight: 900
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenMaruGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenMaruGothic-Light.ttf
          weight: 300
