// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPbkJJilQF0MtOEolats8tg5V7MQUXKWo',
    appId: '1:64609432781:android:1cf09b675a7482f4db2584',
    messagingSenderId: '64609432781',
    projectId: 'aizuchi-dotlog',
    databaseURL:
        'https://aizuchi-dotlog-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aizuchi-dotlog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmp1wpTj7EDCt7N_G0ll1zVn4JefzCgEM',
    appId: '1:64609432781:ios:d7f9aa1e2865c8b4db2584',
    messagingSenderId: '64609432781',
    projectId: 'aizuchi-dotlog',
    databaseURL:
        'https://aizuchi-dotlog-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aizuchi-dotlog.appspot.com',
    iosClientId:
        '64609432781-v0fdcd7abpp1fpeuvavl4rqhtfagbvft.apps.googleusercontent.com',
    iosBundleId: 'jp.co.dotlog.aizuchi.dev',
  );
}
